/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'leona_000' at '10/11/15 11:41 PM' with Gradle 2.3
 *
 * @author leona_000, @date 10/11/15 11:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
